#!/bin/bash
# allow_usb-c_thunderbolt
# Enables thunderbolt interface after USB-C device is plugged in

# Copyright (C) 2014-2015 Alexander Swen <alex@swen.nu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# 2018-08-23 A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)


# FUNCTIONS
die () {
  rc=$1
  shift
  printf '%s\n' "=====================" >&2
  printf '%s\n' "==== FATAL ERROR ====" >&2
  printf '%s\n\n' "=====================" >&2
  printf '%s\n\n' "$@" >&2
  exit $rc
}

log () { printf '%s %s\n' "$(date +%F' '%T)" "$@"; }

get_device_info () {
  local device_available=0
  if [ -L /sys/bus/thunderbolt/devices/0-1 ];then
    local device_available=1
  else
    die 1 "Device not connected."
  fi
}

get_state () {
  local state=$(cat /sys/bus/thunderbolt/devices/0-1/authorized)
  if [ "$state" == "1" ];then
    log "Device already authorized"
    exit 0
  fi
}

enable_thunderbolt () {
  log "Enabling USB-C device..."
  echo 1 > /sys/bus/thunderbolt/devices/0-1/authorized
}

# SCRIPT
[ ${UID} -gt 0 ] && die 1 "Only root may do that."
log "Started ${me}"

get_device_info

get_state

enable_thunderbolt

log "Finished"
# END
