#!/bin/bash
# backup-to-usb-disk
# makes a backup of some dirs to a usb disk if present
# starten kan met konsole --notoolbar --notabbar --nomenubar -T BACKUP --vt_sz 157x55 -e /data/scripts/backup-to-usb-disk
# of gnome-terminal --window-with-profile=HIER --hide-menubar --geometry=112x50 -t "homedir naar server"  --working-directory="/home/alex"  -e '/data/scripts/backup-to-usb-disk'

# Alexander Swen
# Private contact: alex@swen.nu, 06-21811135

# CHANGELOG:
# 2009-05-27	A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)
netwerkmap=/netwerk/home-${LOGNAME}
dirs="~"

# FUNCTIONS
die () {
  rc=$1
  shift
  echo "================================" >&2
  echo "====      FATAL  ERROR      ====" >&2
  echo "================================" >&2
  echo "" >&2
  echo $@ >&2
  echo " "
  echo "Er is iets mis!"
  echo "Bel Alex en vertel hem de error die hierboven staat."
  echo "druk op een enter om dit scherm te sluiten"
  read whatever
  exit $rc
}

do_sync () {
  [ -z "${1}" ] && die 4 something went wrong. call admin
  echo "backing up ${1}..."
echo " "
  /usr/bin/rsync -zav --no-perms --no-owner --no-group "${1}/" ${netwerkmap}
  echo " "
}
# SCRIPT
echo "Checking if disk is mounted..."

for dir in ${dirs};do do_sync "${dir}";done

echo " "
echo " "
echo "alles wat je hierboven ziet is gebackupped  (plus alles wat al was gebackupped natuurlijk)"
echo "(er staan ook voor elke dir samenvattingen, als er geen files genoemd worden is er kennelijk"
echo "niets veranderd. niets om je zorgen over te maken dus)."
echo " "
echo "druk op een enter om dit scherm te sluiten"
read whatever

# END
