#!/bin/bash
# backup-to-usb-disk
# makes a backup of some dirs to a usb disk if present
# starten kan met konsole --notoolbar --notabbar --nomenubar -T BACKUP --vt_sz 157x55 -e /data/scripts/backup-to-usb-disk

# Copyright (C) 2014-2015 Alexander Swen <alex@swen.nu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# 2009-05-27	A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)
usb_disk=/media/500G_usb
dirs="/data/home/irene/Documents /data/mp3 /data/foto"

# FUNCTIONS
die () {
  rc=$1
  shift
  echo "==========================">&2
  echo "====    FATAL  ERROR  ====" >&2
  echo "==========================">&2
  echo "" >&2
  echo $@ >&2
  echo " "
  echo "Er is iets mis!"
  echo "Bel Alex en vertel hem de error die hierboven staat."
  echo "druk op een enter om dit scherm te sluiten"
  read whatever
  exit $rc
}

do_sync () {
  [ -z "${1}" ] && die 4 soemthing went wrong. call alex
  echo "backing up ${1}..."
echo " "
  sudo /usr/bin/rsync -hrav --no-perms --no-owner --no-group "${1}" ${usb_disk}
  echo " "
}
# SCRIPT
echo "Checking if disk is mounted..."
[ "$(mount|grep "${usb_disk}")" = "" ] && die 1 usb disk ${usb_disk} not mounted.

for dir in ${dirs};do do_sync "${dir}";done

echo " "
echo " "
echo "alles wat je hierboven ziet is gebackupped  (plus alles wat al was gebackupped natuurlijk)"
echo "(er staan ook voor elke dir samenvattingen, als er geen files genoemd worden is er kennelijk"
echo "niets veranderd. niets om je zorgen over te maken dus)."
echo " "
echo "druk op een enter om dit scherm te sluiten"
read whatever

# END
