#!/bin/bash
# backup-homedir-harm`
# makes a backup of some dirs to network

# Copyright (C) 2014-2015 Alexander Swen <alex@swen.nu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# starten kan met konsole --notoolbar --notabbar --nomenubar -T BACKUP --vt_sz 157x55 -e /data/scripts/backup-to-usb-disk
# of gnome-terminal --window-with-profile=HIER --hide-menubar --geometry=112x50 -t "homedir naar server"  --working-directory="/home/alex"  -e '/data/scripts/backup-to-usb-disk'

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# 2009-05-27	A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)
rsyncopts="-av --no-perms --no-owner --no-group --exclude=lost+found --exclude=.cache --exclude=.thumbnails --delete --size-only"

# FUNCTIONS
die () {
  rc=$1
  shift
  printf '%s\n' "=====================" >&2
  printf '%s\n' "==== FATAL ERROR ====" >&2
  printf '%s\n\n' "=====================" >&2
  printf '%s\n\n' "$@" >&2
  printf '%s\n' "Er is iets mis!"
  printf '%s\n' "Bel Alex en vertel hem de error die hierboven staat."
  printf '%s\n' "Druk op een enter om dit scherm te sluiten"
  read whatever
  exit $rc
}

get_options () {
  [ $# -gt 0 ]||usage
  while getopts "s:d:" opt;do
    case ${opt} in
      s) export source="`echo $OPTARG`" ;;
      d) export destination="`echo $OPTARG`" ;;
      *) usage;;
    esac
  done
  unset OPTIND
}

log () { printf '%s %s\n' "$(date +%F' '%T)" "$@"; }

# SCRIPT
get_options $@

[ -n "$source" ] || dir="/home/$LOGNAME/DOCUMENTEN"
[ -n "$destination" ] || destination=/netwerk/home-$LOGNAME

log "Backing up $source naar $destination."
/usr/bin/rsync $rsyncopts "$source" "$destination"

log " "
log "alles wat je hierboven ziet is gebackupped  (plus alles wat al was gebackupped natuurlijk)"
log "(er staan ook voor elke dir samenvattingen, als er geen files genoemd worden is er kennelijk"
log "niets veranderd. niets om je zorgen over te maken dus)."
log " "
log "druk op een enter om dit scherm te sluiten"
read whatever

# END
