#!/bin/bash
# brightctl
# adds or subtrackts from the brightness setting

# Copyright (C) 2014-2015 Alexander Swen <alex@swen.nu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# 20140520	A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)

# FUNCTIONS
die () {
  rc=$1
  shift
  echo "==========================">&2
  echo "====    FATAL  ERROR  ====" >&2
  echo "==========================">&2
  echo "" >&2
  echo $@ >&2
  exit $rc
}

usage () {
  echo "==========================" >&2
  echo "====       USAGE      ====" >&2
  echo "==========================" >&2
  echo "" >&2
  echo "Usage: ${me} <up> or <down>" >&2
  echo "" >&2
  echo "example: ${me} up" >&2
  echo "" >&2
  exit 1
}

# SCRIPT
[ ${UID} -gt 0 ] && die 1 only root may do that
case $HOSTNAME in
  nac36663|nvc3691)
    ctlfile=/sys/class/backlight/intel_backlight/brightness
    max_brightness=19200
    ;;
  laptop-nico-aardbei)
    ctlfile=/sys/class/backlight/acpi_video0/brightness
    max_brightness=1500
    ;;
  *)
    die 1 "Dunno the ctlfile."
  ;;
esac
[ -f ${ctlfile} ] || die 2 controlfile ${ctlfile} not found

br=$(cat ${ctlfile})

# vary in steps
if [ $br -ge $((max_brightness-100)) -a $1 == "up" ];then
  step=$((max_brightness-$br))
elif [ $br -le $max_brightness -a $br -gt 1000 ];then
  step=100
elif [ $br -le 1000 -a $br -gt 100 ];then
  step=50
elif [ $br -le 100 -a $br -gt 10 ];then
  step=10
elif [ $br -le 10 ];then
  step=1
fi

case $1 in
  up) newbr=$((br+step));;
down) newbr=$((br-step));;
  *) usage;;
esac
echo ${newbr} > ${ctlfile}

# END
