#!/bin/bash
# mouse_scroll
# Sets the scroll direction to "natural"

# Copyright (C) 2014-2015 Alexander Swen <alex@swen.nu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# 2019-07-09	A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)

# FUNCTIONS
die () {
  rc=$1
  shift
  printf '%s\n' "=====================" >&2
  printf '%s\n' "==== FATAL ERROR ====" >&2
  printf '%s\n\n' "=====================" >&2
  printf '%s\n\n' "$@" >&2
  exit $rc
}

usage () {
  printf '%s\n' "===============" >&2
  printf '%s\n' "==== USAGE ====" >&2
  printf '%s\n\n' "===============" >&2
  printf '%s\n' "Usage: ${me} " >&2
  printf '%s\n\n' "example: ${me} " >&2
  exit 1
}
get_options () {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --thing1|-a)
        shift
        declare -r thing="$1"
        shift
        ;;
      --thing2|-b)
        shift
        declare -r other_thing="$1"
        shift
        ;;
      -h|--help)
        usage
        ;;
      *)
        usage
        ;;
    esac
  done
}

duration () {
  local before=$1
  local after="$(date +%s)"
  local elapsed="$(expr $after - $before)"
  local hours=$(($elapsed / 3600))
  local elapsed=$(($elapsed - $hours * 3600))
  local minutes=$(($elapsed / 60))
  local seconds=$(($elapsed - $minutes * 60))
  time_running="${hours}:${minutes}:${seconds}"
}

log () { printf '%s %s\n' "$(date +%F' '%T)" "$@"; }

# SCRIPT
xinput list|awk -F 'id=' '/MX Anywhere|Mouse/ {print $2}'|awk '{print $1}'|while read id;do
  device_name="$(xinput list --name-only $id)"
  log "Device=$device_name"
  natural_scroll_option_status=$(xinput --list-props $id|awk '/Natural Scrolling Enabled \(/ {print $6}')
  log "ID=$id, name=$device_name and Natural scrolling status=$natural_scroll_option_status"
  xinput set-int-prop $id "libinput Natural Scrolling Enabled" 8 1
  xinput list-props $id |grep "Natural Scrolling Enabled ("

  # When "Logitech USB Laser Mouse" is present:
  if [[ "$device_name" == "Logitech USB Laser Mouse" ]];then
    log "Increase speed of $device_name."
    xinput set-prop $id "Coordinate Transformation Matrix" 2 0 0 0 2 0 0 0 1
    xinput list-props $id |grep "Coordinate Transformation Matrix"
  fi
  echo
done


# END
