#!/bin/bash
# mouse_scroll
# Sets the scroll direction to "natural"

# Copyright (C) 2014-2015 Alexander Swen <alex@swen.nu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# 2019-07-09	A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)

# FUNCTIONS
die () {
  rc=$1
  shift
  printf '%s\n' "=====================" >&2
  printf '%s\n' "==== FATAL ERROR ====" >&2
  printf '%s\n\n' "=====================" >&2
  printf '%s\n\n' "$@" >&2
  exit $rc
}

usage () {
  printf '%s\n' "===============" >&2
  printf '%s\n' "==== USAGE ====" >&2
  printf '%s\n\n' "===============" >&2
  printf '%s\n' "Usage: ${me} " >&2
  printf '%s\n\n' "example: ${me} " >&2
  exit 1
}
get_options () {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --thing1|-a)
        shift
        declare -r thing="$1"
        shift
        ;;
      --thing2|-b)
        shift
        declare -r other_thing="$1"
        shift
        ;;
      -h|--help)
        usage
        ;;
      *)
        usage
        ;;
    esac
  done
}

duration () {
  local before=$1
  local after="$(date +%s)"
  local elapsed="$(expr $after - $before)"
  local hours=$(($elapsed / 3600))
  local elapsed=$(($elapsed - $hours * 3600))
  local minutes=$(($elapsed / 60))
  local seconds=$(($elapsed - $minutes * 60))
  time_running="${hours}:${minutes}:${seconds}"
}

log () { printf '%s %s\n' "$(date +%F' '%T)" "$@"; }

# SCRIPT
xinput list|grep Mouse|while read device;do
  eval $(echo $device|grep -Eo 'id=[0-9]{2}')
  natural_scroll_option_code=$(xinput --list-props $id|awk '/Natural Scrolling Enabled \(/ {sub (/\(/, "");sub (/\)/, "");sub (/\:/, "");print $5}')
  xinput set-int-prop $id $natural_scroll_option_code 8 1
done

# END
