#!/bin/bash
# networktoggle
# toggles wifi on and off
# requires the following in /etc/sudoers
#  <username> ALL=NOPASSWD: /sbin/dhclient

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# 20130902	A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)


# SCRIPT

netstate=$(/usr/bin/nmcli nm wifi|awk '/enabled|disabled/ {print $1}')

case ${netstate} in
  enabled )
    echo "wifi is ${netstate}. It will be disabled now"
    /usr/bin/nmcli nm wifi off
    sudo ip link set dev eth0 up
    sudo dhclient eth0
  ;;
  disabled )
    echo "wifi is ${netstate}. It will be enabled now"
    sudo ip link set dev eth0 down
    /usr/bin/nmcli nm wifi on
  ;;
esac
# END
