#!/bin/bash
# networktoggle
# toggles wifi on and off
# requires the following in /etc/sudoers
#  <username> ALL=NOPASSWD: /sbin/ifup and down

# Copyright (C) 2014-2015 Alexander Swen <alex@swen.nu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# 20130902	A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)


# SCRIPT

netstate=$(/usr/bin/nmcli nm wifi|awk '/enabled|disabled/ {print $1}')

case ${netstate} in
  enabled )
    echo "wifi is ${netstate}. It will be disabled now"
    /usr/bin/nmcli nm wifi off
    sudo ifup eth0
  ;;
  disabled )
    echo "wifi is ${netstate}. It will be enabled now"
    sudo ifdown eth0
    /usr/bin/nmcli nm wifi on
  ;;
esac
# END
