#!/bin/bash
# touchpadtoggle
# toggles touchpadoff setting. This is to enable and disable the touchpad while typing on my laptop

# Copyright (C) 2014-2015 Alexander Swen <alex@swen.nu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# 20130902	A.Swen	created.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)


# SCRIPT

tpstate=$(synclient -l|awk '/TouchpadOff/ {print $3}')

if [ ${tpstate} -eq 0 ];then
  synclient TouchpadOff=1
else
  synclient TouchpadOff=0
fi

# END
