#!/bin/bash
# whichnix
# tries to figure out on what OS it's executed and returns that as output

# Copyright (C) 2014-2015 Alexander Swen <alex@swen.nu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# based on script found at http://www.unix.com/302211858-post6.html posted by a user known as "nobo"
# 2011-08-24 	A.Swen	created.

# TODO
# make proper use of lsb_release package or skip this entire script as lsb_release can tell it all

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)


# FUNCTIONS
die () {
  rc=$1
  shift
  echo "==========================">&2
  echo "====    FATAL  ERROR  ====" >&2
  echo "==========================">&2
  echo "" >&2
  echo $@ >&2
  exit $rc
}

giveUp () {
  echo "Unknown"
  exit 0
}

# keep this easily awkable, prepending an initial clue
versionGuess () {
  if [ -e /proc/version ]; then
    echo -n "Unsure "
    cat /proc/version
    exit 0
  fi
  return 1
}

# if we have ignition, print and exit
gotDist () {
   [ -n "$1" ] && echo "$1" && exit 0
}

# we are only interested in a single word "dist" here
# various malformations can occur; admin will have to code appropately based on output
linuxRelease () {
  if [ -r /etc/lsb-release ]; then
    dist=$(grep 'DISTRIB_ID' /etc/lsb-release | sed 's/DISTRIB_ID=//' | head -1)
    gotDist "$dist"
  fi

  dist=$(find /etc/ -maxdepth 1 -name '*release' 2> /dev/null|sed -e 's/\/etc\///' -e 's/-release//' -e 's/_release//'|head -1)
  gotDist "$dist"

  dist=$(find /etc/ -maxdepth 1 -name '*version' 2> /dev/null|sed -e 's/\/etc\///' -e 's/-version//' -e 's/_version//'|head -1)
  gotDist "$dist"

  return 1
}

# SCRIPT
# start with uname and branch the decision from there
dist=$(uname -s 2> /dev/null)
if [ "$dist" = "Linux" ]; then
  linuxRelease
  versionGuess
  giveUp
elif [ -n "$dist" ]; then
  echo "$dist"
  exit 0
else
  versionGuess
  giveUp
fi

# we shouldn't get here
giveUp
# done

# END
