#!/bin/bash
# zoom-launcher
# Launches zoom after it disabled Linux' screenblank and enables it afterwards

# Copyright (C) 2014-2015 Alexander Swen <alex@swen.nu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# 20200326 A.Swen	created.
# 20201103 A.Swen Add a dirty way to tune the camera a bit.

# SETTINGS
date=$(date +%Y%m%d)
me=$(basename $0)
mydir=$(dirname $0)
video_device=/dev/video4

# FUNCTIONS

saver_on () {
  xset s default
  xset +dpms
}

saver_off () {
  xset s off
  xset s noblank
  xset -dpms
}

# SCRIPT

saver_off
v4l2-ctl -d $video_device --set-ctrl=white_balance_automatic=0,power_line_frequency=1
v4l2-ctl -d $video_device --set-ctrl=white_balance_temperature=3200,sharpness=200
# Since the latest version of Zoom (6.2.0) screensharing resulted in a black
# window for me, while remote viewers are able to see my shared object.
# I found that xcompmgr helps fixing it:
# https://support.zoom.com/hc/nl/article?id=zm_kb&sysparm_article=KB0060528#collapseLinux
# https://wiki.archlinux.org/title/Xcompmgr#Toggle_Xcompmgr is the place where I
# found this command.
xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
zoom
pkill xcompmgr
saver_on
# END
